/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#fcf9f8",
        "on-secondary-fixed-variant": "#00497e",
        "on-tertiary-container": "#ffbe95",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        background: "#fcf9f8",
        "tertiary-container": "#7e4924",
        "primary-container": "#006064",
        "on-primary": "#ffffff",
        secondary: "#0061a6",
        "secondary-fixed-dim": "#a0caff",
        error: "#ba1a1a",
        "on-surface-variant": "#3f4949",
        "surface-variant": "#e5e2e1",
        "status-pending": "#F47738",
        tertiary: "#62330f",
        "on-primary-fixed": "#002021",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#8ad3d7",
        "tertiary-fixed-dim": "#ffb688",
        "secondary-container": "#6eb2fe",
        "on-secondary-container": "#004376",
        primary: "#00464a",
        "surface-container-highest": "#e5e2e1",
        outline: "#6f7979",
        "on-background": "#1c1b1b",
        "inverse-surface": "#313030",
        "on-secondary-fixed": "#001c37",
        "border-subtle": "#D1D5DB",
        "tertiary-fixed": "#ffdbc7",
        "status-valid": "#00703C",
        "on-error": "#ffffff",
        surface: "#fcf9f8",
        "on-error-container": "#93000a",
        "on-primary-container": "#8fd8dc",
        "surface-container-low": "#f6f3f2",
        "inverse-primary": "#8ad3d7",
        "surface-tint": "#14696d",
        "surface-container": "#f0eded",
        "status-revoked": "#D4351C",
        "on-surface": "#1c1b1b",
        "inverse-on-surface": "#f3f0ef",
        "primary-fixed": "#a6eff3",
        "on-tertiary-fixed": "#311300",
        "outline-variant": "#bec8c9",
        "on-tertiary-fixed-variant": "#6b3a16",
        "surface-container-high": "#eae7e7",
        "surface-dim": "#dcd9d9",
        "on-primary-fixed-variant": "#004f53",
        "secondary-fixed": "#d2e4ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        base: "8px",
        "container-max": "1280px",
        gutter: "16px",
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "code-sm": ["Inter", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "code-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
